### ISSUE TITLE
Ixia Container - Data interfaces - eth1, eth2

### ISSUE THREAD

**Issue by anursharma** [open-traffic-generator/ixia-c#83] opened 2022-06-20 22:20 UTC

**Comment by ashutshkumr** [comment] 2022-06-21 10:38
@anursharma could you please review this issue ? is it a duplicate of https://github.com/open-traffic-generator/ixia-c/issues/84 ?

**Comment by ankur-sheth** [comment] 2022-08-11 18:41
Looks like a duplicate of #84.  Closing this one.

**Closed by ankur-sheth** 2022-08-11 18:41 UTC
